### ISSUE TITLE
关于dataset和生成keyphrases的一点问题

### ISSUE THREAD

**Issue by hit-computer** [memray/seq2seq-keyphrase#1]
您好。我看您的论文里提到了dataset已经公开了，请问我在哪儿可以获得50多万的论文数据啊？还有一个关于模型的问题，您是用seq2seq模型来生成keyphrases的，在预处理数据时一篇论文会被拆分成好几个数据，也就是说在训练模型的时候Encoder同一个文本时会Decoder出好几个不同的keyphrases，对应于机器翻译的话就是同一个原文会有很多不同的译文版本，是这样的吗？那么在测试过程中，输入一篇新的text，如何Decoder得到多个keyphrases啊，比如在计算 F@5 时，是Encoder输入文本后，利用Beam Search进行Decoder结束后将最大堆中的top-5返回的吗？  谢谢 :)

**Comment by memray** [comment]
Hi, 抱歉才回复，github的信息发到我以前邮箱了。数据最近正在整理（确实不该拖这么久 = =），希望很快就会release。
关于训练过程你的理解是对的。我把一篇论文的abstract和多个keyphrases重新拆成多个<abstract,keyphrase> pairs，然后放到seq2seq里面去训练。Decode的时候就是用Beam Search返回top K结果作为预测的关键词。

**Comment by hit-computer** [comment]
@memray 明白啦，谢谢了 :)
