### ISSUE TITLE
ERROR incurred when running on Tesla GPU

### ISSUE THREAD

**Issue by leexian** [memray/seq2seq-keyphrase#13]
Could someone help?

I tried to run this project on GPU to get a speedup. But error incurred. What's the correct way? What should I do to configure the env?

command:
THEANO_FLAGS='floatX=float32,device=cuda' CUDA_VISIBLE_DEVICES=1 python keyphrase_copynet.py

error info:
ERROR (theano.gpuarray): pygpu was configured but could not be imported or is too old (version 0.7 or higher required)

**Comment by memray** [comment]
Looks like a Theano setting problem. Could you check if [this](https://github.com/Theano/libgpuarray/issues/514) would be helpful?

**Comment by leexian** [comment]
thank memray
problem solved by updating pygpu : conda install -c conda-forge pygpu
