### ISSUE TITLE
关于环境配置的问题

### ISSUE THREAD

**Issue by flycorn1** [memray/seq2seq-keyphrase#17]
您好，我想知道您当时运行这程序的关于deep learning方面环境的版本 theano版本 cuda版本 显卡型号等等。我不清楚我的机器是否能成功运行这个程序    我现在也遇到了 ValueError: zero-size array to reduction operation maximum which has no identity  （issue#10）这个错误 ，当运行copynet.py的时候。我怀疑可能和我环境配置有关系，非常感谢！

**Comment by memray** [comment]
你好，
我觉得可能是test data没有成功加载。因为我几个文件都是分开release的，所以可能带来不少混乱。你有检查#10里面提到的几个配置和路径吗？
我之前训练是GTX 980ti, cuda=8.0, theano>=0.7
