### ISSUE TITLE
training——dataset

### ISSUE THREAD

**Issue by pierre-zhao** [memray/seq2seq-keyphrase#19]
Thanks for  sharing your  code. I'm a little confused about this json file showed below which i cannot find in filefolder： /dataset/keyphrase
![1](https://user-images.githubusercontent.com/34771910/38617013-61aa0c90-3d85-11e8-9c7c-842f39dbede6.JPG)

**Comment by memray** [comment]
I removed it from the latest release because it's rarely used. You can download it from [here](https://drive.google.com/open?id=0B-7HD48qQzxVQ3hIMW5NY1RWQ0E).

It is almost same to the json dump located in dataset/keyphrase/punctuation-20000validation-20000testing/json_dump/

**Comment by pierre-zhao** [comment]
So, the training_dataset is located in  dataset/keyphrase/punctuation-20000validation-20000testing/
all_600k_dataset.pkl?
![2](https://user-images.githubusercontent.com/34771910/38652909-880b3676-3df7-11e8-9a87-4d4fa54ee5ab.JPG)

**Comment by pierre-zhao** [comment]
After reading #8 , I understand the function of  all_600k_dataset.pkl which used for training, validation(indexes in validation_id_20000.pkl ) and testing(indexes in testing_id_20000.pkl) . But I still have some questions about word embedding.
1.In seq2seq structure, input sequence for encoder is based on word embedding. So for the dataset,  is it embedded by seq2seq-keyphrase-master\emolga\layers\embeddings.py( this is a embedding layer? )?
2.Is One-hot vector for dataset  presented by 
punctuation-20000validation-20000testing/all_600k_voc.json?

**Comment by memray** [comment]
0. Yes, you are right regarding the id. The all_600k_dataset.pkl contains both training and validation data.
1. Yes, it is the embedding layer. It is mostly called in encoding (inside emolga.models.covc_encdec and emolga.models.encdec).
2. all_600k_voc.json is just a byproduct I used for checking the quality of vocabulary. All the data examples in all_600k_dataset.pkl have been processed to one-hot vectors (word id is assigned according to its word frequency from large to small). They are further processed by unk_filter() in keyphrase/keyphrase_copynet.py to replace long-tail words (word_id > voc_size) with '<unk>'.

**Comment by pierre-zhao** [comment]
Very thankful !  I will read the code (emolga.models.covc_encdec and emolga.models.encdec)carefully.

**Comment by pierre-zhao** [comment]
Sorry , another question #_# :Embedding matrix is pre-trained or trained in encoding(where can I find the process of forming the embedding matrix)?

**Comment by memray** [comment]
No pre-trained vector is used. Word embeddings are initialized randomly and learned during the training :D

**Comment by pierre-zhao** [comment]
Thx!
