### ISSUE TITLE
word vector

### ISSUE THREAD

**Issue by suppppppper** [memray/seq2seq-keyphrase#21]
Excuse me,

Can you ask how the word vector is trained?

Where is the code implementation?

Thank you very much!

**Comment by memray** [comment]
Word embedding is initialized randomly (no pre-trained things) and learned along with RNN during the training.

**Comment by suppppppper** [comment]
Where is the code that implements the word vector training process?

Is in emolga/models/encdec/class Encoder #word embedding?

**Comment by memray** [comment]
Yes, that's where embedding is defined.

**Comment by suppppppper** [comment]
I got it

Thank you very much!
