### ISSUE TITLE
Question about code 

### ISSUE THREAD

**Issue by pierre-zhao** [memray/seq2seq-keyphrase#22]
Hi ! Memray:

Sorry to bother u again , I have two questions about the code. 

1. What's the difference between covc_encdec.py and encdec.py ?
2. I'm a little confused about code parameter "context" in the embeddings.py and "use_context"in encoder.

Thanks u for explanation.

**Comment by pierre-zhao** [comment]
After thinking carefully, I seem to know the meaning of "context" , which is aimed at presenting context matix [nb_sample, max_len].

**Comment by memray** [comment]
Hi!
1. covc_encdec.py implements the CopyNet, but encdec.py is only about vanilla RNN.
2. I didn't use the **enc_use_context** (in config.py), so I am not quite sure how it works. I think it's like using the contextual information to affect the embedding.

**Comment by pierre-zhao** [comment]
very thankful !
In the config.py,  line 15 ,is the config['model_name'] useful?  I set the config['model_name'] =TfIdf for using TfIdf.  But it does not seem to work.
Is the baseline implementations from Kazi Saidul Hasan in your paper?

**Comment by memray** [comment]
'model_name' is used in keyphrase/baseline/evaluate.py (line 341), mostly for telling the path from where we can load the predicted phrases of these baseline models.
Yes, I ran their C implementations.

**Comment by huangjiatang** [comment]
Hi, @memray,  great work! 
I'm trying to reuse this code to build my own model.
I was hoping that you can share a bit more about your training experience.
For example, how long it takes to make the model converge,  to get a comparable result as in the paper?

**Comment by memray** [comment]
Hi @huangjiatang. I trained it on GTX 980 ti and it took roughly 2~3 days to finish. I didn't tune it very much, so I guess the performance could be better than the one reported in the paper. BWT, I would suggest you use this [PyTorch implementation](https://github.com/memray/seq2seq-keyphrase-pytorch).

**Comment by huangjiatang** [comment]
Thanks a lot!
We'll give it a try.

**Comment by pierre-zhao** [comment]
Hi !

Sorry to bother u again.  After careful thinking, I'm still a little confused about one  part of  DecoderAtt showing below:
![default](https://user-images.githubusercontent.com/34771910/40428719-7ff80584-5ed3-11e8-88e0-6ca455d39b23.JPG)
1, What is the function of Eng?
2. Is the next_c used for copy-mode? and is the next_b used for generate-mode? 
3. In your code, which used coverage trick , is the sum_a used for that purpose?

**Comment by memray** [comment]
Sorry I don't really remember these details. The model part was originally implemented by [Jiatao Gu](https://github.com/MultiPath/CopyNet). I added some comments in [conv_encdec.py](https://github.com/memray/seq2seq-keyphrase/blob/cfb2e00bfbae406b87fb09803d76f69bf6f19535/emolga/models/covc_encdec.py#L992). Hope they are helpful.

**Comment by pierre-zhao** [comment]
Thanks a lot ! Your comments are very useful !
After reading your comments , I have some thinking about the code of copynet.  In your comments (line 977) ,for computing the copy attention weights, you did not find a non-linear activation function like Eq.8.  Here, I think Os layer (line 975) is the non-linear layer,  which projects r_in (mixed decoder hidden layer) into the same semantic space with encoder hidden layer. So my opinion is different with Eq.8  -_-:  and Eq.8 should be  φ_c=h_j *σ(W_c *s_t) ...But it seems not correct ,because the location for copying is determined by source ,rather than target.

**Comment by memray** [comment]
The code is not super readable, so I had a bad time associating it with the paper. The comments present my best understanding but may not be correct. I think you are right regarding the Os layer. I find that the default activation function is tanh, which I overlooked previously. I don't have comment on the other part. I [re-implemented](https://github.com/memray/seq2seq-keyphrase-pytorch) it mostly based on my understanding instead of this code, because I found the former is easier :D

**Comment by pierre-zhao** [comment]
Hi! Memray:
    Recently, I made a small  change  on your model and I want to verify the ability of the model on the DUC dataset. Can you send me the text folder /dataset/keyphrase/baeline-data/DUC (2001) tested in your model. Thinks a lot!

**Comment by memray** [comment]
Please check this [file](https://drive.google.com/open?id=1xtGNGm63dAuuuEXk4B_4hy4VDBytrGj_) out. Place it to /baseline-data/.

**Comment by pierre-zhao** [comment]
Thank you very much!!

**Comment by pierre-zhao** [comment]
Sorry to bother you again,  the folder /duc/keyphrase is empty...  In the [folder](https://drive.google.com/open?id=1xtGNGm63dAuuuEXk4B_4hy4VDBytrGj_), there is just the text

**Comment by memray** [comment]
It seems I didn't export it to that folder. Can you do it yourself? All the ground-truth phrases can be found in /testing-data/DUC/keyphrase/DUC2001LabeledKeyphrase.txt

**Comment by pierre-zhao** [comment]
Sure, I will do it myself. Thanks for your help!

**Comment by pierre-zhao** [comment]
Hi ! memray :
    Recently, I have a problem when training the model, so I would like to consult your experience . 
    In your paper, your model is trained for 4 epochs. As mentioned above, it took roughly 2~3 days to finish . But in my training process,  it takes roughly 3 days to finish one epoch( My gpu is 1070).  Is your pytorch implementation  faster than theano in training process? If so, I will learn it.  
    My hyperparameters : config['batch_size'] = 64 , config['mini_mini_batch_length']=50000( I have tried larger mini_mini_batch_length , Ex. 100000, but convergence speed will be slower)

**Comment by pierre-zhao** [comment]
Oops! I forgot to ask you a question. What is your final loss_reg ?  -_-:

**Comment by memray** [comment]
Hi,

I feel pytorch implementation is much faster and easier-to-debug. But the final performance might be different (for now, its score is a little worse than Theano). The setting of mini_mini_batch_length is a bad tradeoff due to the small GPU memory, and I guess it slows down the training a little bit. I don't remember the loss_reg and I cannot find it. Sorry about it.

Rui

**Comment by pierre-zhao** [comment]
Rui :
Thanks a lot ! You are so kind and helpful .
