### ISSUE TITLE
A question about the "Micro" and the "Macro" averaging methods in evaluation.

### ISSUE THREAD

**Issue by Chen-Wang-CUHK** [memray/seq2seq-keyphrase#23]
Hi Memray,
    Your implementation of the "Micro" averaging method actually is Macro-averaged ?
    Your implementation of the "Macro" averaging method actually is Micro-averaged ?
    Looking forward to your reply！

**Comment by memray** [comment]
Hi Chen,

Thank you for bringing this up. You are right these two are reversed and I didn't correct it appropriately until now. The true micro was ignored and not reported. As far as I can recall, the two numbers would be very close if the dataset is large enough. 

Here is a new and correct [implementation](https://github.com/memray/seq2seq-keyphrase-pytorch/blob/adab882b677ba1c1fe8dd4ecfc02a0e7a9c6d62a/evaluate.py#L243) you may like to refer to, and only macro-average is provided. Sorry about the confusion.

Rui

**Comment by Chen-Wang-CUHK** [comment]
Dear Rui Meng,
    Thank you for such a quick reply!
    According to your definition in the paper (" Following the standard
definition, precision is defined as the number of correctly-predicted
keyphrases over the number of all predicted keyphrases, and recall is
computed by the number of correctly predicted keyphrases over the total
number of data records."), you actually used the true Micro but you called
it "macro" in the paper.
    More importantly, the two numbers are not that close on your released
KP20K keyphrase output of the test set. Only the true Micro-averaged scores
are very close to your reported scores in the paper.

Best,
Wang

Rui Meng <notifications@github.com> 於 2018年8月24日 週五 上午12:24寫道：

**Comment by memray** [comment]
Hi Wang,

I checked the previous result. The difference between micro and macro is mostly less 0.1 and either one is significantly better than baselines. I will check it in more detail and mention the error in erratum if necessary.

Thank you,
Rui
