### ISSUE TITLE
Is there a code version writed by TensorFlow?

### ISSUE THREAD

**Issue by VieZhong** [memray/seq2seq-keyphrase#25]
RT.

**Comment by memray** [comment]
I don't know any dedicated TF implementation, but I think this [code](https://github.com/abisee/pointer-generator) is usable as it also supports a copy mechanism.

**Comment by VieZhong** [comment]
Thank you very much.

Hi, I have an another question.
How do you use the stop words? In another word, when the stops words in the dataset will be used in your trainning process?

Thx again.

**Comment by memray** [comment]
I didn't remove stopwords by heuristics, i.e. all words are used in training. But the vocabulary only contains most frequent 50k words out of 300k (all words in the corpus). Other words are replaced by ``UNK''.

**Comment by VieZhong** [comment]
Thank you for your answer.

I want to confirm that if the output result is the keyphrase no matter how many words in it?  

How do you handle the keyphrases that contain more than 2 words, such as `computer science`?

**Comment by memray** [comment]
Yes, one phrase may contain more than 1 word, and the model is generating a phrase word by word.
