### ISSUE TITLE
Data Gathering

### ISSUE THREAD

**Issue by ygorg** [memray/seq2seq-keyphrase#27]
Hi, thank you for sharing your code and the data you gathered.
I was wondering if were planning on publishing an article describing the kp20k dataset (as it is (to my knowledge) the biggest available dataset for keyphrase extraction), and how, where and when did you collect the data?
Are the gold keyphrases created by authors or users ?

**Comment by memray** [comment]
Hi @ra1nbowpill ,

Thank you for your interest. Yes, the gold keyphrases are from authors. I just collected/crawled metadata of scientific papers from different digital libraries (ACM, Wiley etc.) a few years ago. I think it might be hard to do outside the campus (I guess only university/research institute buy these digital resources). 

Thanks,
Rui
