### ISSUE TITLE
Absent keyphrase benchmarking numbers

### ISSUE THREAD

**Issue by laurita** [memray/seq2seq-keyphrase#28]
Hi @memray

I am able to reproduce the numbers published in your paper for the present keyphrases but not for the absent ones. I thought maybe you will have an insight into what I am doing wrong. The prediction data that I am using for evaluation was downloaded from your google drive on 6 Feb, 2019, the seq2seq-keyphrase repository was cloned on 12 Feb, 2019. 

As parameters in the config for the absent test I use (see also attached patch code) 
model= CopyRNN_absent, 
predict_type generative, 
predict_filter: non-appear-only
target_filter non-appear-only. 

The metrics I get vs the expected ones:

Dataset  |CopyRNN (paper) | CopyRNN (I got)
------------ | ------------- | -------------
. | R@10 / R@50 | R@10 / R@50
Inspec | 0.051 / 0.101 | 0.00000 / 0.001952
Krapivin | 0.116 / 0.195 | 0.005940 / 0.017970
NUS | 0.078 / 0.144 | 0.002892 / 0.006479
SemEval | 0.049 / 0.075 | 0.005540 / 0.009127
KP20k | 0.115 / 0.189 | 0.075402 / 0.172163

Best,
Laura

[CopyRNN_absent_patch.txt](https://github.com/memray/seq2seq-keyphrase/files/2856055/CopyRNN_absent_patch.txt)
[experiments.baseline.id=20190212-132601.log](https://github.com/memray/seq2seq-keyphrase/files/2856061/experiments.baseline.id.20190212-132601.log)

**Comment by memray** [comment]
Hi Laura,

Sorry, I don't have any clue just based on the results. Could you please print the generated phrases and ground-truth, and check what's going on? I suspect the **target_filter** on the first four datasets is problematic. The distribution of Krapivin is very similar to KP20k, thus the performance gap looks bizarre.

Thanks,
Rui

**Comment by laurita** [comment]
Hi memray,

Thank you for your answer. In terms of the **target_filter**, I would be surprised if this was the case as I have tried different combinations of the **target_filter** and **predict_filter** values but I will look into that, thanks!

Could you please check the absent keyphrase prediction files under the `dataset/keyphrase/prediction/CopyRNN_absent/<dataset>/` in the zipfile that you have linked in the README? To me the absent keyphrases seem suspiciously unrelated to the corresponding texts. Could it be the case that the numbered text files are mixed up?

For example, for the file `dataset/keyphrase/baseline-data/inspec/text/0.txt`:

1. true keyphrases (`dataset/keyphrase/baseline-data/inspec/keyphrase/0.txt`) are:
out of print materials
library materials
out of print books
changing practices
recurring issues
acquisition
2. predicted present keyphrases (`dataset/keyphrase/prediction/CopyRNN_present/inspec/0.txt.phrases`) are:
libraries
print materials
weak collections
print literature
strong collections
missing copies
recurring issues
duplicate copies
fill gaps
acquiring out of print
acquiring out of print materials 
3. predicted absent keyphrases (`dataset/keyphrase/prediction/CopyRNN_absent/inspec/0.txt.phrases`) are:
game theory
cooperative game
characteristic function
cooperative game theory
game game
nash equilibrium
game design
computational game theory
graph theory
computer games
combinatorial games
algorithmic game theory
game game theory
classical game theory
social networks
social games
unique solution
combinatorial optimization
cooperative game game
...

See the example below
(top left = text, top right = true keyphrases, bottom left = present predicted keyphrases, bottom right = absent predicted keyphrases)
![inspec0example](https://user-images.githubusercontent.com/1272844/53428204-aaab6300-39ea-11e9-8072-de16118db8d1.png)

**Comment by memray** [comment]
I think you are right. We also found this mistake. I run the experiments on different platforms and didn't assign unique ids causes this problem. I am sorry about that.

**Comment by laurita** [comment]
Thank you for responding quickly! Do you have plans to release the correct predictions for the CopyRNN_absent?

**Comment by memray** [comment]
I cannot run the Theano implementation now, thus I don't really know how to help in this regard. I apologize for this mess. AFAIK the absent prediction contains present keyphrases as well, so maybe you can follow this idea to reveal the real ordering according to the present prediction. If it works out, please let me know and I can update my release.
