### ISSUE TITLE
Can not download training data

### ISSUE THREAD

**Issue by CQRachel** [memray/seq2seq-keyphrase#3]

**Comment by memray** [comment]
To me, all the links are working. Which file have you tried?

**Comment by CQRachel** [comment]
Thanks for your reply. I've tried both http://crystal.exp.sis.pitt.edu:8080/iris/data/experiment_dataset.zip and http://crystal.exp.sis.pitt.edu:8080/iris/data/kp20k.zip. They are provided in your description.

**Comment by memray** [comment]
The server is running properly now and I can download two files well. Could you help me check it out again? The server is not very powerful and responsive. So you'd better try some software that could resume downloads.

**Comment by CQRachel** [comment]
Yeah, all the links are working now. Thanks a lot.
Also thanks for your suggestion. I tried IDM, the speed reaches 0.5M/s. 
Awesome.
