### ISSUE TITLE
Is there a pretrained model available ?

### ISSUE THREAD

**Issue by pidugusundeep** [memray/seq2seq-keyphrase#31]
Hey @memray , 
I have a newer version of UBUNTU and I cannot really use CUDA 8.0 as it doesn't support ubuntu 18.04, so just wanted to know if you rather have a pre-trained model available to download so that I can use that for testing.

**Comment by pidugusundeep** [comment]
As described here :
https://github.com/memray/seq2seq-keyphrase/blob/cfb2e00bfbae406b87fb09803d76f69bf6f19535/keyphrase/config.py#L435

By any chance, I can get this pre-trained model.

**Comment by pidugusundeep** [comment]
I was able to download that model and tried to run ```keyphrase_copynet.py``` with only setting ```do_predict = True``` while I was not able to figure out where exactly the keyphrases are getting generated and stored at the end

**Comment by memray** [comment]
Hi @pidugusundeep,

I would suggest you use this [repo](https://github.com/memray/seq2seq-keyphrase-pytorch) instead. Theano itself is no longer updated and I can run the model after upgrading the Ubuntu. For the PyTorch implementation, for now I don't have any pre-trained model to release. It takes only ~1day to train on KP20k with 1 GPU, so I think training it from scratch won't be a problem.

Best,
Rui

**Comment by pidugusundeep** [comment]
@memray thanks for the clarification, I was able to run this repo and do the predictions but where exactly are the final results stored? is that here? https://github.com/memray/seq2seq-keyphrase/blob/7d989d351d0606106d93ee775ccd63a69ac8fa6b/keyphrase/config.py#L123  

If so how do I get the exact keyphrases which are predicted?

**Comment by memray** [comment]
It should be in the folder as you set. It has been a while and I don't remember the detail now.
