### ISSUE TITLE
About Micro and Macro scores

### ISSUE THREAD

**Issue by shizhediao** [memray/seq2seq-keyphrase#34]
In your paper, there is a clarification about the evaluation scores.
I konw the difference between micro and macro scores.
I was wondering why you choose Macro-averaged score in your paper?
Are there any justifications?
Thanks very much!

**Comment by memray** [comment]
In our case, `macro-averaged` is the doc-level average score. We think it makes more sense because the number of keyphrases varies doc by doc. Mix them together may lose this per-doc information. Hope this clarifies your question. 

Rui
