### ISSUE TITLE
一个问题

### ISSUE THREAD

**Issue by fst813** [memray/seq2seq-keyphrase#36]
你好！我想问下在生成keyphrase的时候怎么确定生成结束的呢？也就是生成的长度如何确定的？是有一个结束标记然后预测出结束标记的概率最大吗？

**Comment by memray** [comment]
是的，有个EOS (end of sequence) token作为结束的标志。
这个repo已经不再维护了，建议用这个repo里的代码（https://github.com/memray/OpenNMT-kpg-release）。
