### ISSUE TITLE
关于模型OOV的一些问题

### ISSUE THREAD

**Issue by o-github-o** [memray/seq2seq-keyphrase#4]
你好，在训练模型时encode指定了一个固定大小的vocab_size,decoder Copynet的copy部分是怎么去识别copy词表外的word的呢，训练中词表外的word都表示为了unknown.

**Comment by memray** [comment]
CopyRNN是由两个部分组成，一个是generate mode（普通RNN，只能预测预设的voc中的词，假设size=10000）一个是copy mode（pointer network，以所有input text中出现的词作为voc）。

在input text进行预处理时，其中一个步骤就是识别出来哪些位置上的词在vocabulary中以及哪些不在，假设input text = {x1,x2...x55}，其中x1-x50在voc中，而x51-x55不在，这样这里有5个词是out-of-vocabulary。

对于generate mode来说，那些不在预设voc中的词（x51-x55）都已经被替换为unknown，每步只考虑voc中那10000个词的概率。而copy mode是计算每个位置的概率，也就是说在predict的每一步会计算x1-x55这55个位置上的词应当被输出的概率。

最后在beam search的时候generate的概率和copy的概率会merge起来，也就是说每步计算的是10005个词的概率。当copy mode认为那5个词概率很高的时候（即便generate mode那边不认识他们），也就会输出出来了。不知道这样讲解是否清晰一些 :D

**Comment by CQRachel** [comment]
你好，
copyRNN能预测input text以外的词么：假设input text = {x1,x2...x55}，其中x1-x50在voc中，而x51-x55不在，那可能输出{x1,x2...x55}以外的词么？
疑惑的是：CopyNet原文中写了 y∉voc∪X 时的概率。

**Comment by memray** [comment]
可以的，这就是generate mode的作用了，通过生成模型输出即便是在input中没有出现过，但是语义上相关的词汇。我不知道你疑惑的是CopyNet paper的哪部分内容。

**Comment by CQRachel** [comment]
O(∩_∩)O谢谢回答，
CopyNet paper中公式7，generate-mode：φ=vWs，v∈voc∪unk；
文中提到v是一个one-hot向量，那么假设词表中有N个词，对于不在词表及input text中的（任何）词，v就是用[0,0,...,0,1]（N个0和一个1）表示的么？

**Comment by memray** [comment]
generate-mode是只能预测词表voc中的词汇，不在词表中的词它完全不会考虑。我觉得这里提到one-hot可能有点misleading，公式7的意思就是告诉我们yt = vi时generate-mode的概率应该怎么得到。程序里是直接通过矩阵运算一次得到所有词的概率，而不是一个一个one-hot得到。

**Comment by CQRachel** [comment]
O(∩_∩)O谢谢，看了你的解释更清楚一些了。
那么就上面的意思来看，generate-mode和copy-mode加起来只能预测 voc∪input_text 中的词汇，但是看文中的意思，CopyNet能预测 voc∪input_text 以外的词吧？
具体依据为：①Figure 2中描述的4-class分类器，有给出yt∉voc∪input_text时的条件概率，②公式7后面提到Wo是个（N+1）×ds的矩阵，而不是N×ds，我以为vi的最后一行应该就是代表voc∪input_text以外的词。不知道这么想对不对。

**Comment by memray** [comment]
您可能还是有一点点误解。
①generate-mode只能预测voc中的词（比如前面例子中的1w个），copy-mode能预测的是所有input中的词（前面例子中的55个词）。因此由copy-mode预测的部分中还包含5个在voc之外的词 {yt ∈ input_text ∩ yt ∉ voc}。而整个CopyNet能预测的词是voc∪input_text∪UNK。
②公式7提到了vi ∈ V ∪ UNK。N是voc的size，所以我觉得那个1只是指UNK。

**Comment by CQRachel** [comment]
thanks~but I guess I'm still confused. Silly me.

我再顺下思路：
① generate-mode只预测 voc 中的词，1w；
② copy-mode只预测 input_text 中的词，55；
③ 两个加起来就是CopyNet，只预测出 voc∪input_text 中的词，1w+55-50=1w+5；

那么问题来了(O_O)：
① UNK指代any out of vocabulary word，那么UNK应该不只包括 “5个在voc之外的词 {yt ∈ input_text ∩ yt ∉ voc}”，还有一些 “voc∪input_text ”以外的词，也就是说CopyNet能预测 1w+5+∞ 个词？
② 我也认为 vi 的那个1是指UNK（vi ∈ V ∪ UNK），那么假设generate-mode预测出yt是UNK，而且yt不在input_text中，那么生成的词会是什么呢？

**Comment by memray** [comment]
①UNK不是指代，它只是用来在预处理的时候把所有低频词替换掉，以减少voc的大小。因此这些“voc∪input_text ”以外的词在数据中都不存在了，训练和测试的时候也完全不会被用到。
②那么生成的词就是UNK。所以CopyNet还是会有UNK的问题，只是说一定程度上减少了很多。Copy对于摘要之类的问题比较有帮助，对于翻译估计就不会了。

**Comment by CQRachel** [comment]
原来是这样O(∩_∩)O，谢谢~

**Comment by memray** [comment]
:D

**Comment by ybshen007** [comment]
你好，关于OOV有个问题想请教。
对于CopyNet中的公式4，P(next_word)=p(next_word,generate-mode)+p(next_word,copy-mode)。
第一项是generate-mode得到的概率，即voc中1w个词；第二项是copy-mode得到的概率，即55个位置。那请问这两项相加是指？当前55个input中有50个在voc内，所以是把50个加到第一项对应位置上，剩下5个concat到1w后面组成10005吗？
另外，如果按照上述处理，那对一个batch来说，decoder得到的output应该是一个1w+{batch中input包含oov最大值}规模的vector，然后取最大位置的id作为当前的输出词？如此一来，对1w以上部分，batch中每个case对应的含义应是不同的，这不会造成影响吗？
谢谢。

**Comment by memray** [comment]
机理的确如你所述，但pointer的作用只是指向source里的不同位置（假设55个位置），本身并不考虑太多semantics，然后通过一个data-specific的mapping将这55个位置上的概率映射到vocab上（10005个，也可能是其他数字，依情况batch里的oov word数目而定）。还有个地方需要clarify，最后是取整个10005个字里预测概率最大的字作为输出，而不是“取最大位置的id作为当前的输出词”。

**Comment by ybshen007** [comment]
既对于每个batch来说，当前这一次的train词表大小是动态变化的？
比如我第一个batch中OOV有5个，则当前batch词表大小是10005；第二个batch中OOV有10个，则当前batch词表大小是10010？

**Comment by memray** [comment]
嗯嗯是的，其实是有效的vocab size是浮动的，但为了实现方便，其实是预设了一个max_oov_size（比如100），这样每次返回的logit size一直都是10100，但其实只有在batch中出现的oov词部分的logit有意义(比如10000到10010)，后面的词都是0（最后90个id）。

**Comment by ybshen007** [comment]
嗯嗯多谢，还有最后一个关于具体细节的问题。
按照这种做法，在具体实现的时候，其实我的词表大小应该是开一个更大的值，比如10100。然后在设计word dictionary的时候，取1w个常用词编号为1-1w（包含一些特殊符号，如PAD等）。然后对一个batch中不在这1w范围内的词，分别编号为10001、10002等。
如果以上说法正确，那比如同一个batch中，第一个句子有一个OOV词，为它编号10001。第二个句子也有一个不同的OOV词，这时是编号为10001还是10002呢？

**Comment by memray** [comment]
如果是不同的词就是10002了。我们的目的就是为每个batch里的unique新词建立一个临时vocab以及一个position-to-word的mapping list，保证最后pointer产生的对于每个position的probs能够通过这个临时vocab和mapping转回成词的概率。不知道这样说你有更清楚一些吗~

**Comment by ybshen007** [comment]
那我清楚啦，多谢多谢！
