### ISSUE TITLE
Running of keyphrase/baseline/evaluate.py causes error

### ISSUE THREAD

**Issue by ottj** [memray/seq2seq-keyphrase#6]
I would like to reproduce the results in the paper, hence run keyphrase/baseline/evaluate.py.
I get the following error:
AttributeError: 'module' object has no attribute 'setup_keyphrase_baseline'

The current version of the config.py file does not contain a setup_keyphrase_baseline method.

**Comment by memray** [comment]
Gosh I must have cleaned the code too much. It should be working now.

BTW, you can find the implementation of baseline models from [Kazi Saidul Hasan](http://www.hlt.utdallas.edu/~saidul/code.html) (TfIdf, TextRank, SimpleRank, ExpandRank) and [Alyona Medelyan](http://www.medelyan.com/software) (Maui and KEA).

I just put my keyphrase outputs [here](http://memray.me/uploads/data/prediction.zip) for your convenience (unzip to `seq2seq-keyphrase-release/dataset/keyphrase/prediction`). Then you don't have to rerun all the models.

**Comment by boudinfl** [comment]
Thanks @memray for uploading your outputs.

I have one question concerning the output format: are keyphrases sorted by importance (i.e. keyphrase on line one is more probable than keyphrase on line two, etc.)?

Also, what is the mapping between your file names (i.e. 0.txt.phrases, 1.txt.phrases, etc.) and the original file names (C-1.txt, C-14.txt, etc.). I suppose it corresponds to the lexical order of the input files.

Last question, what is the standard output of your model for semeval : CopyRNN_present_singleword=1 or CopyRNN_absent?

Best,

**Comment by memray** [comment]
1. Yes, they are sorted by importance. 
2. Yes. I renamed these files alphabetically for convenience.
3. Each folder has an output of semeval (as well as for other datasets). The groundtruth is placed in the folder `dataset/keyphrase/testing-data`.

**Comment by boudinfl** [comment]
Thanks again @memray 

So I've re-computed the f-scores of some of your prediction files using the official semeval-2010 scorer and the combined (author+reader) references file. Reference and candidate keyphrases are compared in their stemmed form.

model                                             |  F@5  | F@10 | F@15
---------------------------------|-------|-------|------
CopyRNN_absent                          | 16.27  |  17.26 | 17.05
CopyRNN_present_singleword=1 | 17.53  | 20.47 | 19.80
TfIdf                                               |  6.64  | 11.27  | 12.88

What is the difference between the absent and present_singleword=1 variants of CopyRNN? And what variant did you use in Table 2 of your [ACL paper](http://memray.me/uploads/acl17-keyphrase-generation.pdf) ?

Best,

f.

**Comment by memray** [comment]
**present_singleword=1** is for Table 2, which means these phrases appear in the source text. 
**absent** is for Table 3, on the contrary, means the source text doesn't contain these phrases.
