### ISSUE TITLE
cannot download training dataset kp20k

### ISSUE THREAD

**Issue by antolli** [memray/seq2seq-keyphrase#7]
Good morning, 
I've tried to download the training data Kp20k provided in your description: http://crystal.exp.sis.pitt.edu:8080/iris/data/kp20k.zip, but the link doesn't working.
Could you verify this problem?
Thank you,
Best,

**Comment by memray** [comment]
Try this please: [http://memray.me/uploads/data/experiment_dataset.zip](http://memray.me/uploads/data/experiment_dataset.zip)
