### ISSUE TITLE
训练集问题

### ISSUE THREAD

**Issue by lihy-1224** [memray/seq2seq-keyphrase#8]
Hi，请问‘punctuation-20000validation-20000testing’里的每个文件的作用是什么呀，初学NLP有些不太懂，all_600k_dataset.pkl是所有raw数据吗？如果是的话，请问如何直接使用其它格式的文件作为训练集，比如kp20k数据集中的json格式？

**Comment by memray** [comment]
`all_600k_dataset.pkl` contains all the data examples of kp20k, in which around 530k examples are for training, 20k for validating and 20k for testing.
`validation_id_20000.pkl` and `testing_id_20000.pkl` indicate the indexes of validation data and testing data in the `all_600k_dataset.pkl` respectively. Note that each file is very small, as only an array of indexes is included.
`all_600k_voc.json` and `all_600k_voc.pkl` are all words in the vocabulary sorted by frequency. I remember they are not used in the model.
`inspec.testing.pkl` is a small testing dataset for simple evaluation during training.

**Comment by lihy-1224** [comment]
OK, I got it! But if I want to use my own data for training dataset, do I have to use  "/keyphrase/dataset/keyphrase_dataset.py" to generate the pickled data?

**Comment by memray** [comment]
Yes, I think these two lines below matter most, but I've commented them in the code. Other lines are trivial, mostly about exporting something for data analysis:
`
train_set, test_set, idx2word, word2idx = load_data_and_dict(config['training_dataset'], config['testing_dataset'])`
`
serialize_to_file([train_set, test_set, idx2word, word2idx], config['dataset'])
`

**Comment by lihy-1224** [comment]
Thx, I understood it after reading your codes and paper carefully. But one thing still confuses me is  the role of 'title' in your dataset, which contains 'abstract', 'title' and 'keyword'. Can I use a dataset without 'title'?

**Comment by memray** [comment]
Sure, I think you can leave the `title` blank. Because I concatenate the `title` and `abstract` to obtain the source text. You could customize your own preprocessing as well.

**Comment by lihy-1224** [comment]
OK👌. May I ask you another question? I think `config['testing_datasets']` indicates the datasets for extracting keyphrase, but what about `config['testing_dataset']`, what is it used for? Besides, I found the `text` in `dataset/baseline-data/` folder is preprocessed by nltk.pos_tag(), but it seems unavailable for Chinese language. So I wanna know whether this project could be used for Chinese keyphrase extraction, or some codes in the project should be modified?

**Comment by memray** [comment]
`config['testing_dataset']` is not very useful, only used for some quick testing during training.
And you are right about the purpose of `config['testing_datasets']`.

I didn't try with Chinese therefore I cannot help too much. If you want to adapt my English model to Chinese data directly, I don't think it will work. If you mean to retrain the model on Chinese data, I see no problems. The only concern is the preprocessing part, which you may have to change the tokenization module and etc. I think the nltk.pos_tag() only works for the evaluation part.

**Comment by lihy-1224** [comment]
Yes, I has followed your instructions to retrain the model and generate training and testing dataset. 

But when I set `config['do_predict'] = True`, I could't see it extracted phrases into `dataset/keyphrase/prediction/`. Only when I set `config['do_evaluate'] = True`, the result in `dataset/keyphrase/prediction/` is created. 

So could you tell me which part of your codes is used for extracted phrases into `dataset/keyphrase/prediction/ `? Because I didn't find it😓.

Sorry to bother you again.

**Comment by memray** [comment]
It's true that `do_predict` doesn't export the final keyphrases. It's because during predicting the model (deep model) would generate decode_logits (indexes of words) based on the given input text, but not really readable strings yet. Thus in the next step `do_evaluate`, a post-processing would convert these logits into strings. And the exporting process is located in `keyphrase_utils.py` from line 359 to line 367.

**Comment by lexus1224** [comment]
Hi, 我尝试通过训练自己的模型并预测关键词，但并没有得到预期的结果，生成的prediction文件均为空的，但用你提供的pretrained model进行预测是可以得到正确结果的。

我的训练过程是这样的：
首先生成一个json格式的文件，为了节省时间我选取kp20k.json里的前1000条item作为训练集，然后反注释`keyphrase_dataset.py`里的两行代码：
`train_set, test_set, idx2word, word2idx = load_data_and_dict(config['training_dataset'], config['testing_dataset'])`
`serialize_to_file([train_set, test_set, idx2word, word2idx], config['dataset'])`
然后运行`keyphrase_dataset.py`生成对应的pkl文件。
其中`config['training_dataset']`指向原始的json文件，`config['testing_dataset']`指向一个空的文件，`config['dataset']`则指向生成的pkl文件。

config.py中的参数设置：
`config['do_train'] = True`
`config['do_quick_testing'] = False`
`config['do_validate'] = False`
`config['do_predict'] = True`
`config['do_evaluate'] = True`
`config['testing_datasets'] = ['inspec', 'nus', 'semeval', 'krapivin', 'kp20k'中的任一个]`

并注释掉以下三行：
    `config['validation_size'] = 20000`
    ` config['validation_id']   = config['path'] + '/dataset/keyphrase/'+config['data_process_name']+'validation_id_'+str(config['validation_size'])+'.pkl'`
    `  config['testing_id']      = config['path'] + '/dataset/keyphrase/'+config['data_process_name']+'testing_id_'+str(config['validation_size'])+'.pkl'`
其余均与默认值保持一致。

最后运行`keyphrase_copynet.py`, 提示199行
`train_set, validation_set, test_sets, idx2word, word2idx = deserialize_from_file(config['dataset'])`报错：`ValueError: need more than 4 values to unpack`，原因是`config['dataset']`中没有`validation_set`, 因此将其修改为`train_set, test_sets, idx2word, word2idx = deserialize_from_file(config['dataset'])`后可以成功运行，训练完成后进行预测时，在终端输出的结果均为`get 1 outputs`，并且prediction文件夹中的文件内容为空。

请问你有遇到过这种情况吗？或者你觉得上述过程是否存在不妥之处呢？非常感谢~
