### ISSUE TITLE
Transfer raw data to the same format in baseline-data

### ISSUE THREAD

**Issue by lostnighter** [memray/seq2seq-keyphrase#9]
I want to extract keyphrases from my own data using the model, but how to transfer raw data to the same format in baseline-data? what is the processing flow or call some func?

**Comment by memray** [comment]
The line 518 of [keyphrase_copynet.py](https://github.com/memray/seq2seq-keyphrase/blob/d919407fd1263cc6a7e01f1b470f5725267d46ef/keyphrase/keyphrase_copynet.py#L518) will load the external dataset according to the given `dataset_name`. I did implement some loading [func](https://github.com/memray/seq2seq-keyphrase/blob/d919407fd1263cc6a7e01f1b470f5725267d46ef/keyphrase/dataset/keyphrase_test_dataset.py#L787) for a few datasets and you can customize a loader for your own data. Basically there is just one function `get_docs()` needs implementing.
